# Dockerfile.worker
FROM keyboard-base

# Копируем весь код в контейнер
WORKDIR /app
COPY . /app

ENV PYTHONPATH=/app

ENV DATA_KEY=control:metrics

# Запуск скрипта воркера
CMD ["python", "models/worker_rabbit.py"]