name: CI tests

on:
  push:
    branches: [ dev, "feature_*", "*test*", "fix_*" ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo systemctl start docker
          docker --version

      - name: Build base image first
        run: |
          docker compose build base


      - name: Build Docker images
        run: |
          docker compose build

      - name: Start Redis and wait for it
        run: |
          docker compose up -d redis
          sleep 10  # Ждем запуска Redis

      - name: Run tests in analyzer container
        run: |
          docker compose run --rm analyzer pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Stop containers
        if: always()
        run: |
          docker compose down